# Generated by Django 5.1.3 on 2024-11-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_comments_todolist_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.ManyToManyField(blank=True, to='client.comment'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='comments',
            field=models.ManyToManyField(blank=True, to='client.comment'),
        ),
    ]
